sudo: required
language: python

# command before installation: install all dependencies and run CMAKE config
before_install:
  - sudo apt-get install gfortran
  - mkdir -p usr
  - export FORTRAN_INSTALL_DIR=$TRAVIS_BUILD_DIR/usr
  - mkdir build && cd build
  - cmake -DCMAKE_Fortran_FLAGS="-fPIC" -DBUILD_TESTING=ON -DCMAKE_INSTALL_PREFIX=$FORTRAN_INSTALL_DIR  ..
  - cd ..

# command to install project
install:
  - cd build && make && make install && cd ..

before_script:
  - mkdir pytest
  - cp mpi_tester.py pytest

# command to run tests
script:
  - cd build ; make test ; cd ..

